version: 0.2


env:
  variables:
    BUCKET_NAME: enterprise-loyalty-dashboard-beta
    REACT_APP_BUILD_VARIANT: dev
  parameter-store:
    NPM_TOKEN: "/CodeBuild/shoutout/github/token"
phases:
  install:
    commands:
      - echo Entered the install phase...
      - rm .npmrc
      - echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "@shoutout-labs:registry=https://npm.pkg.github.com/shoutout-labs" >> .npmrc
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run build:staging:github
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Uploading the artifacts to S3 bucket
      - aws s3 cp build s3://enterprise-loyalty-application-beta-xhste/ --recursive
      - echo TODO Creating an invalidation on Cloud Front distribution
      - aws cloudfront create-invalidation --distribution-id E1TADGUN44NE7F --paths "/index.html" --query Invalidation.Status
      - echo Build completed on `date`